export const dataDefaultSteps = [
  {
    steps: 0,
    text: "Muchas gracias por tu interés en conocer customerScoops, que a través de Formularios Conversacionales Inteligente te ayudamos a aumentar el revenue y rentabilidad de tu negocio.",
    question: "Queremos conocerte, ¿cuál es tu nombre?",
    input_type: "text",
    default_values: [],
    value: "name",
    label: "Comenzar",
  },
  {
    steps: 1,
    text: ", ahora nos gustaría tener cierta info para diseñar una gran propuesta de valor para ti:",
    question: "¿Cuál es tu cargo/posición dentro de tu empresa?",
    input_type: "select",
    default_values: [
      "Board member",
      "C-level",
      "Gerente",
      "Subgerente",
      "Jefe área",
      "Líder de área",
      "Ejecutivo / Analista",
      "Otro",
    ],
    value: "position",
    label: "Siguiente",
  },
  {
    steps: 2,
    text: "",
    question: "¿Cuáles son tus principales desafíos para 2024?",
    input_type: "select",
    default_values: [
      "Aumentar conversiónde leads a clientes",
      "Reducir customer churn",
      "Implementar un programa VoC",
      "Reducir costos en gestión de reclamos",
      "Optimizar procesos comerciales",
      "Optimizar procesos operativos",
      "Otro",
    ],
    value: "challenge",
    label: "Siguiente",
  },
  {
    steps: 3,
    text: "",
    question: "¿Cuál CRM están utilizando en tu empresa?",
    input_type: "select",
    default_values: [
      "SAP",
      "Microsoft Dynamics",
      "Salesforce",
      "Hubspot",
      "Zoho",
      "Netsuite (Oracle)",
      "Monday",
      "CRM Propio",
      "No tengo CRM",
    ],
    value: "crm",
    label: "Siguiente",
  },
  {
    steps: 4,
    text: "Ahora te vamos a sorprender... ",
    question: "¿A cuál industria pertenece tu empresa?",
    input_type: "select",
    default_values: [
      "Tecnología",
      "Software",
      "Servicios",
      "Financiera",
      "Telecomunicaciones",
      "Producción /Fabricación",
      "Logística",
      "Consumo Masivo",
      "Mayorista",
      "Retail",
      "Otra",
    ],
    value: "industry",
    label: "Siguiente",
  },
  {
    steps: 5,
    text: "Muchas Gracias ",
    question: "por querer ser parte de la familia Scoopers. Nos vemos pronto",
    input_type: undefined,
    default_values: [],
    label: "Finalizar",
    value: "Finish",
  },
];
